export const keyToMeshMap = {
  key_a: "a",
  key_b: "b",
  key_c: "c",
  key_d: "d",
  key_e: "e",
  key_f: "f",
  key_g: "g",
  key_h: "h",
  key_i: "i",
  key_j: "j",
  key_k: "k",
  key_l: "l",
  key_m: "m",
  key_n: "n",
  key_o: "o",
  key_p: "p",
  key_q: "q",
  key_r: "r",
  key_s: "s",
  key_t: "t",
  key_u: "u",
  key_v: "v",
  key_w: "w",
  key_x: "x",
  key_y: "y",
  key_z: "z",
  key_0: "0",
  key_1: "1",
  key_2: "2",
  key_3: "3",
  key_4: "4",
  key_5: "5",
  key_6: "6",
  key_7: "7",
  key_8: "8",
  key_9: "9",
  key_space: "space",
  key_shift_left: "shift_left",
  key_shift_right: "shift_right",
  key_ctrl_left: "ctrl_left",
  key_ctrl_right: "ctrl_right",
  key_alt_left: "alt_left",
  key_alt_right: "alt_right",
  key_enter: "enter",
  key_backspace: "backspace",
  key_tab: "tab",
  key_capslock: "capslock",
  key_esc: "esc",
  key_win_left: "win_left",
  key_win_right: "win_right",
  key_menu: "menu",
  key_dash: "dash",
  key_equals: "equals",
  key_open_bracket: "open_bracket",
  key_close_bracket: "close_bracket",
  key_backslash: "backslash",
  key_colon: "colon",
  key_quote: "quote",
  key_comma: "comma",
  key_dot: "dot",
  key_question: "question",
};

export const keyToCharMap = {
  key_a: "a",
  key_b: "b",
  key_c: "c",
  key_d: "d",
  key_e: "e",
  key_f: "f",
  key_g: "g",
  key_h: "h",
  key_i: "i",
  key_j: "j",
  key_k: "k",
  key_l: "l",
  key_m: "m",
  key_n: "n",
  key_o: "o",
  key_p: "p",
  key_q: "q",
  key_r: "r",
  key_s: "s",
  key_t: "t",
  key_u: "u",
  key_v: "v",
  key_w: "w",
  key_x: "x",
  key_y: "y",
  key_z: "z",
  key_0: "0",
  key_1: "1",
  key_2: "2",
  key_3: "3",
  key_4: "4",
  key_5: "5",
  key_6: "6",
  key_7: "7",
  key_8: "8",
  key_9: "9",
  key_space: " ",
  key_dash: "-",
  key_equals: "=",
  key_open_bracket: "[",
  key_close_bracket: "]",
  key_backslash: "\\",
  key_colon: ";",
  key_quote: "'",
  key_comma: ",",
  key_dot: ".",
  key_question: "/",
  key_enter: "\n",
  key_tab: "    ",
};

export const shiftKeyMap = {
  key_1: "!",
  key_2: "@",
  key_3: "#",
  key_4: "$",
  key_5: "%",
  key_6: "^",
  key_7: "&",
  key_8: "*",
  key_9: "(",
  key_0: ")",
  key_dash: "_",
  key_equals: "+",
  key_open_bracket: "{",
  key_close_bracket: "}",
  key_backslash: "|",
  key_colon: ":",
  key_quote: '"',
  key_comma: "<",
  key_dot: ">",
  key_question: "?",
};

export const letterKeys = [
  "key_a",
  "key_b",
  "key_c",
  "key_d",
  "key_e",
  "key_f",
  "key_g",
  "key_h",
  "key_i",
  "key_j",
  "key_k",
  "key_l",
  "key_m",
  "key_n",
  "key_o",
  "key_p",
  "key_q",
  "key_r",
  "key_s",
  "key_t",
  "key_u",
  "key_v",
  "key_w",
  "key_x",
  "key_y",
  "key_z",
];

export const ignoredKeys = [
  "key_shift_left",
  "key_shift_right",
  "key_ctrl_left",
  "key_ctrl_right",
  "key_alt_left",
  "key_alt_right",
  "key_win_left",
  "key_win_right",
  "key_menu",
  "key_capslock",
];
